// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationType } from "./ConversationType";
import type { MessageType } from "./MessageType";

export type ImMessage = { messageType: MessageType, content: string, sender: string, conversationType: ConversationType, recipient: string, sentAt: string, recievedAt: string | null, updatedAt: string, };
