// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatOperation } from "./ChatOperation";
import type { ConversationType } from "./ConversationType";
import type { MessageType } from "./MessageType";

export type MessageRequest = { operation: ChatOperation, recipient: string, conversationType: ConversationType, messageType: MessageType, content: string, };
